version: 2
jobs:
  backend:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run:
          name: Install plugins
          command: |
            git clone git@github.com:octoberrain/drivers-plugin.git ./plugins/october/drivers
            git clone git@github.com:rainlab/blog-plugin.git ./plugins/rainlab/blog
            git clone git@github.com:rainlab/googleanalytics-plugin.git ./plugins/rainlab/googleanalytics
            git clone git@github.com:rainlab/user-plugin.git ./plugins/rainlab/user
            git clone git@github.com:vuetober/rainlab-user-api.git ./plugins/vuetober/rainlabuserapi
      - restore_cache:
          key: -v3-{{ checksum "composer.lock" }}-{{ checksum "themes/site/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            wget https://getcomposer.org/composer.phar
            php composer.phar install --no-interaction
            sudo composer self-update
            composer install
            (cd ./plugins/speedcube/speedcube && composer install)
            (cd ./themes/site && yarn install)
      - save_cache:
          key: -v3-{{ checksum "composer.lock" }}-{{ checksum "themes/site/yarn.lock" }}
          paths:
            - "vendor"
            - "themes/site/node_modules"
      - run:
          name: Configure environment
          command: |
            cp .env.example .env
      - run:
          name: Test backend
          command: |
            (cd ./plugins/speedcube/speedcube && vendor/bin/phpunit --coverage-clover clover.xml)
      - run:
          name: Codecov
          command: |
            (cd ./plugins/speedcube/speedcube && bash <(curl -s https://codecov.io/bash) -t 5c7c532d-d106-480a-b67e-d2af48ce8f56 -cF php)
  frontend:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: -v3-{{ checksum "themes/site/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            (cd ./themes/site && yarn install)
      - save_cache:
          key: -v3-{{ checksum "themes/site/yarn.lock" }}
          paths:
            - "themes/site/node_modules"
      - run:
          name: Test frontend
          command: |
            (cd ./themes/site && yarn test:unit)
      - run:
          name: Codecov
          command: |
            (cd ./themes/site && bash <(curl -s https://codecov.io/bash) -t 5c7c532d-d106-480a-b67e-d2af48ce8f56 -cF javascript)
  deploy:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploying to production..."
            else
              echo "Deployment aborted for non-master branch."
            fi
workflows:
  version: 2
  tests:
    jobs:
      - backend
      - frontend
      - deploy:
          requires:
            - backend
            - frontend
