version: 2
jobs:
  backend:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run:
          name: Clone Plugins
          command: |
            git clone git@github.com:rainlab/googleanalytics-plugin.git ./plugins/rainlab/googleanalytics
            git clone git@github.com:rainlab/user-plugin.git ./plugins/rainlab/user
            git clone git@github.com:vuetober/rainlab-user-api.git ./plugins/vuetober/rainlabuserapi
      - restore_cache:
          key: -v3-{{ checksum "composer.json" }}
      - run:
          name: Composer Install
          command: |
            wget https://getcomposer.org/composer.phar
            php composer.phar install --no-interaction
            sudo composer self-update
            composer install
      - run:
          name: Yarn Install
          command: |
            cd ./themes/site
            yarn install
      - save_cache:
          key: -v3-{{ checksum "composer.json" }}-{{ checksum "themes/site/yarn.lock" }}
          paths:
            - "composer.lock"
            - "vendor"
      - run:
          name: Test
          command: |
            ls -a
            vendor/bin/phpunit -c ./plugins/speedcube/speedcube/phpunit.xml
workflows:
  version: 2
  tests:
    jobs:
      - backend