name: Build

on: [push]

jobs:
  backend:
    name: Test Backend
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v1
    - name: Copfigure environment
      run: cp .env.example .env
    - name: Copy static assets
      run: cp client/public/index.html plugins/speedcube/speedcube/views/index.htm
    - name: Install October
      run: composer install
    - name: Install plugins
      run: |
        cd plugins/speedcube/speedcube
        composer install
    - name: Install node dependencies
      run: |
        cd client
        npm install
    - name: PHPUnit
      run: |
        cd plugins/speedcube/speedcube
        vendor/bin/phpunit --coverage-clover clover.xml

  frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        cd client
        npm install
    - name: Jest
      run: |
        cd client
        npm run test:unit -- --coverage
    # - name: Report coverage
    #   run: bash <(curl -s https://codecov.io/bash)

  deploy:
    if: github.ref == 'refs/heads/l6'
    name: Deploy
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: curl ${{secrets.ENVOYER_NEXT_URL}}