name: Build

on: [push]

jobs:
  backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
  
  # frontend:
  #   name: Test Frontend
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Install
  #     run: npm install
  #   - name: Test
  #     run: npm test
  #   - name: Report coverage
  #     run: bash <(curl -s https://codecov.io/bash)

  deploy:
    if: github.ref == 'refs/heads/l6'
    name: Deploy
    needs: [backend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: curl ${{secrets.ENVOYER_NEXT_URL}}