name: Build

on: [push]

jobs:
  backend:
    name: Test Backend
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: PHPUnit
      run: |
        cd plugins/speedcube/speedcube
        phpunit --coverage-clover clover.xml

  frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        cd client
        npm install
    - name: Jest
      run: |
        cd client
        npm run test:unit -- --coverage
    # - name: Report coverage
    #   run: bash <(curl -s https://codecov.io/bash)

  deploy:
    if: github.ref == 'refs/heads/l6'
    name: Deploy
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: curl ${{secrets.ENVOYER_NEXT_URL}}